### ISSUE TITLE
索引问题请教

### ISSUE THREAD

**Issue by majiabaomajiabao** [hadyang/interview#15]
https://hadyang.github.io/interview/docs/basic/database/mysql/innodb/index/

这篇文章中的，`User Records 就是整个页面中真正用于存放行记录的部分，而 Free Space 就是空余空间了，它是一个链表的数据结构，为了保证插入和删除的效率，整个页面并不会按照主键顺序对所有记录进行排序，它会自动从左侧向右寻找空白节点进行插入，行记录在物理存储上并不是按照顺序的，它们之间的顺序是由 next_record 这一指针控制的。`，                                        
                       这段话说的记录不一定是顺序的，但           
`B+ 树的叶子节点存放所有指向关键字的指针，节点内部关键字记录和节点之间都根据关键字的大小排列。当顺序递增插入的时候，只有最后一个节点会在满掉的时候引起索引分裂，此时无需移动记录，只需创建一个新的节点即可。而当非递增插入的时候，会使得旧的节点分裂，还可能伴随移动记录，以便使得新数据能够插入其中。`   ，对这两个知识点，不太理解，请问一下这两个点

**Comment by majiabaomajiabao** [comment]
是不是可以理解成页和页之间是顺序的，页内部可以是无序的？

**Comment by hadyang** [comment]
可以这样理解。当一条记录更新或者删除后不会立即删除物理记录，而是通过 next_record 控制，因此在页内部是存在“脏数据”的。 next_record 指针形成的链表是顺序的，页与页之间也是顺序的。

**Comment by majiabaomajiabao** [comment]
好的，多谢
