### ISSUE TITLE
插入排序的时候，内循环 temp < a[j] && j >= 0 这两个条件应该倒过来

### ISSUE THREAD

**Issue by learnice** [hadyang/interview#3]
`while (j >= 0 && temp < a[j]) {
				a[j + 1] = a[j];
				j--;
			}`
感觉这样比较合适，因为当元素要插入到第 0 个元素的时候，此时 j==0，j-- 等于 -1，再进 while 循环判断时数组越界了

**Comment by hadyang** [comment]
非常感谢，代码已修改  @learnice
